### ISSUE TITLE
Transistors from PDF - ValueError: invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by oleg1187** [HazyResearch/fonduer-tutorials#38]
Still having this issue. I am working with Ubuntu 18.04.
Is this a package version problem?

https://gist.github.com/oleg1187/7c74ccafbf8533953fdd658fdeed5182

**Comment by lukehsiao** [comment]
Can you share a document that exhibits the issue?

**Comment by oleg1187** [comment]
I hope you mean the issue template.

Go to "Parser Configuration" and run the code. The parser stops after a short time when I set "parallelism=None". 
When I set "parallelism=PARALLEL" the kernel hangs and I get this document:

![image](https://user-images.githubusercontent.com/31730615/49328185-4b18f500-f56c-11e8-865b-c270f26bfec9.png)

The parser stops after a short time (progress bar: 1%) when I set "parallelism=None". 

The parser stops (progress bar: 10%) when I set "max docs=10" and "parallelism=None".

I also tried changing the database encoding. I am not sure whether there is something wrong with my poppler package. I installed it with conda because that was the most convenient way. But if I try to import poppler, the module is not found though I can find it with conda search:

![image](https://user-images.githubusercontent.com/31730615/49323133-54c43d80-f517-11e8-9a7b-0bbba9aa17d6.png)

OS: Ubuntu 18.04
PostgreSQL Version: 10.5
Poppler Utils Version: 0.65.0 
Fonduer Version: 0.4.0

**Comment by lukehsiao** [comment]
> I hope you mean the issue template.

What you've added is helpful. But, what I'm asking about is what documents are you parsing that is causing the issue. Are you just running one of the tutorials? I see you have created your own file called `hardware_max_storage`. What documents are you parsing?

> I am not sure whether there is something wrong with my poppler package. I installed it with conda because that was the most convenient way. But if I try to import poppler, the module is not found though I can find it with conda search

There is a good chance that this is the issue. I haven't used conda for install poppler, but on Ubuntu 18.04 you can simply run `sudo apt-get install poppler-utils` and it should work just fine.

**Comment by oleg1187** [comment]
hardware_max_storage is just the notebook title. Basically I just tried to run the parser on the "download_data.sh" files, which you provided for the tutorial.
I just uninstalled poppler with conda and installed it with apt-get but still get same error.

Thanks a lot for your help!

**Comment by lukehsiao** [comment]
Unfortunately, without being able to replicate this error I don't have a direct way to help you.

From the code, it's clear that `num_pages` is being calculated incorrectly.

In these lines:

https://github.com/HazyResearch/fonduer/blob/510e274b3fca36977eee80f489a19bf887348f73/src/fonduer/parser/visual_linker.py#L65-L68

You can see that `num_pages` is just taken from the call to `pdfinfo`. You can try directly on the commandline to see what you get in response.

```
$ pdfinfo [FILENAME] | grep - a Pages | sed 's/[^0-9]*//'
```

It sounds to me like there are issues in your environment with poppler-utils. You may also check that `subprocess.check_output` call within Python within your environment to see if there are any discrepancies. We recommend using `virtualenv` rather than conda as described in our [Getting Started](https://fonduer.readthedocs.io/en/latest/user/getting_started.html) page.
